Partially revert "Fixed compilation fail `CContextMenu.cpp(255,20): error C2039: 'BuildMenuTree': is not a member of 'CContextMenu' ` for build run https://github.com/end2endzone/ShellAnything/actions/runs/10540285814/job/29204765722." This reverts commit 12780d7d671c1642db154a052328edddef264106.